### ISSUE TITLE
documenting 'ev'

### ISSUE THREAD

**Issue by soodoku** [GaryBAYLOR/mixR#22]
```
?b.test
```

```
a logical value indicating whether the variance of each component should be the same or not (default FALSE). ev is ignored for other family members.
```

the statement `ev is ignored for other family members' is not clear. need to provide default family (normal) somewhere?

**Comment by GaryBAYLOR** [comment]
Hi @soodoku, this issue is now fixed  in [mixR/R/bs.test.R](https://github.com/GaryBAYLOR/mixR/blob/38b293b34b33ee821d6e85861b2e94a282dbccca/R/bs.test.R#L19) and the corresponding manual file [mixR/man/bs.test.Rd](https://github.com/GaryBAYLOR/mixR/blob/38b293b34b33ee821d6e85861b2e94a282dbccca/man/bs.test.Rd#L33) is also updated accordingly. Thanks!
